### ISSUE TITLE
1kHz pulse

### ISSUE THREAD

**Issue by merbanan** [rpcope1/Hantek6022API#30]
Hi, have there been any though about enable the pulse or even extend the api for it? It should be possible to use a 8051 timer and enable all kinds of pulse lengths.

**Comment by jhoenicke** [comment]
The pulse should work, but I haven't checked it lately.  The code to pulse is `PA7 = !PA7` in `timer2_isr`.  If you want another pulse length, you would need to reprogram the timer2 with a different frequency.  Note that the timer interrupt also drives the LED, so you may want to adapt the ledcounter.

**Comment by merbanan** [comment]
Ok, I only have the Sainsmart to play with, I'll try and see if I can get it working. Would patches for moving  out the led stuff to another timer be welcome ? Or the pulse ? I am not sure what timer has the best properties for generating random pulse lengths.

**Comment by jhoenicke** [comment]
I think the timer0/1 are currently unused, but I'm not sure if they are suitable.  I'm not sure what the future plans for the 6022be driver are.  Probably the sigrok code base will become the reference code.   I haven't tried it yet.

**Comment by merbanan** [comment]
I got this working and I can implement other timings without any problems.
