### ISSUE TITLE
Firmware API

### ISSUE THREAD

**Issue by KimBP** [rpcope1/Hantek6022API#40]
Hi
Great you try to improve on the official Hantek firmware.

Apparently your mod_fw_01.ihex firmware has been applied to the openhantek 6022be branch by swkim01, but I see several different *hex files in you repo. 

I see a stock_fw.ihex which is the official Hantek firmware release something. But what about all your other hex files?
Can't you add some information about the different hex files (including their API). I have looked at your 'custom' folder and it seems like this, if installed, provides a very different API not being compliant to the official Hantek firmware

**Comment by jhoenicke** [comment]
stock is the  official Hantek firmware.

modded contains three patches to the official firmware, fixfiforeset should fix the FIFO reset sequence, samplerates fixes some of the sample rates and provides new ones, e.g. the 24 MSamples/s mode, and isodiff provides a new isochronous transfer mode with guaranteed transfer rate (up to 24 MSamples/s).  The mod_fs_01 firmware contains all but the last one, and mod_fs_iso should contain all three patches.

custom is a complete rewrite of the firmware based on the fx2lib library.  I left out some functionality, e.g. the functionality for reading the eeprom that stores the calibration data.

**Comment by KimBP** [comment]
I haven't made any research on fx2lib so can't yet decide if your custom firmware becomes better than the patched firmware. At least you'll be in full control of all features.

Are you planning to implement some trigger functionality in this driver?
Right now in OpenHantek we have a SW trigger, but you easily loose some data because the trigger is based on findings in a sampling campaign. If the event happen in between two sample campaigns the information is lost. If implemented in firmware the decision can be made after each sample.

**Comment by jhoenicke** [comment]
I'm not sure if HW trigger is even possible.

In principle you can do non-stop sampling to avoid losing the event.  I'm not sure if OpenHantek supports this, though.

**Comment by KimBP** [comment]
If you're in control in the 8051 code it shouldn't be that difficult (I think) - pseudo:
trigval = x; trig_dir=rising;
start sampling into circular buffer
if (sample count > prebuffer) {
   if (sample_prev < x && sample_new >= x) 
       trigged reached - 
       wait for (circular buffer size - prebuffer) samples

Upload samples starting with (trig point - prebuffer)

**Comment by jhoenicke** [comment]
The 8051 cannot keep up with the highest possible sampling rates.  Also the FIFO cannot be used as ring buffer.  Maybe it is possible to clear the last FIFO when no trigger signal is found in the current FIFO and start autotransmit when the trigger signal is found, but it is a lot of work, probably only works for about 1 MSamples/s, and simpler to do on the PC side in a similar fashion.

**Comment by KimBP** [comment]
OK - in case the 8051 can't keep pace it is not possible. I thought the 8051 was responsible for each sample made. Having it handled in the device would be so much better.
When done in SW and you want to show say 8000 of the 10000 samples you have to find the trigger within a range of just 2000 samples in order to produce a 'steady' impression at the screen. 
But of cause if the 'continous mode' is reliable you can in principle at the PC join two sample campaigns.
